<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="0"
            failures="1"
            tests="4">

  <testsuite name="login.sem_sucesso.test"
    errors="0" failures="1" hostname="" id="" package="login" skipped="0"
    tests="4" time="17.39" timestamp="">
  
    <testcase name="senha incorreta" classname="login.sem_sucesso.test" time="3.276" assertions="3">

    

    

    
    </testcase>
  
    <testcase name="nao cadastrado" classname="login.sem_sucesso.test" time="1.290" assertions="3">

    

    

    
    </testcase>
  
    <testcase name="email nao informado" classname="login.sem_sucesso.test" time="3.984" assertions="3">

    

    

    
    </testcase>
  
    <testcase name="senha nao informada" classname="login.sem_sucesso.test" time="8.837" assertions="3">

    

      <failure message="Testing if element &lt;.alert&gt; contains text &#39;Opps. Cadê a senh?&#39; in 5000ms - expected &#34;contains text &#39;Opps. Cadê a senh?&#39;&#34; but got: &#34;does not contain &#39;Opps. Cadê a senh?&#39;&#34; (5063ms)">    at Object.senhaNaoInformada [as senha nao informada] (C:/Users/geovana.amaral/Documents/QANinja/zombieplus/tests/login/sem_sucesso.test.js:52:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)</failure>

    
    </testcase>
  

  

    

  
  </testsuite>
</testsuites>
